# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ATX DEV
email: tw15egan@gmail.com
description: > # A collection of CSS tricks I've picked up along the way, as well as a sprinkle of music I've been enjoying lately.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: tj_egan 
github_username:  tw15egan

permalink: /:title

hex: 
# Build settings
markdown: kramdown
  
exclude: ["node_modules", "gulpfile.js", "package.json"]